language: node_js
node_js:
  - 10
  # - node

os:
- linux
# osx would be great, but travis only supports docker for linux

env:
  # Will override the Travis web UI settings.
  - force_deploy="true"

sudo: true
cache: npm

before_install:
# VS Code requires this to run tests on travis linux
# https://vscode-docs.readthedocs.io/en/latest/extensions/testing-extensions/
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script:
- cd dev/
# install and compile
- npm run vscode:prepublish || travis_terminate 1
# run tests
- ../travis-scripts/run-tests.sh || travis_terminate 1
# package into .vsix
- npm i -g vsce
- vsce package

after_success:
# copy the vsix to the script dir and cd into it
- export artifact_name="$(basename *.vsix)"
- mv -v $artifact_name ../travis-scripts/
- cd ../travis-scripts/
# will exit immediately if not a deploy build
- ./deploy.sh || >&2 echo "Deploy failed!"


notifications:
  email:
    recipients:
      - timetchells@ibm.com
      # - devexbld@us.ibm.com
    on_success: change
    on_failure: change
